### PR TITLE
Bmi array support - Rebase on master

### PR DESCRIPTION
**Pull request by mattw-nws**
[Short description explaining the high-level reason for the pull request]

## Additions

-

## Removals

-

## Changes

-

## Testing

1.

## Notes

-

## Todos

-

## Checklist

- [ ] PR has an informative and human-readable title
- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

## Testing checklist (automated report can be put here)

1.

### Target Environment support

- [ ] Linux

### CODE REVIEW

**Comment by mattw-nws** [comment]
Okay I'm not sure how/why there are conflicts on the last two files (Bmi_Module_Formulation.hpp and Bmi_Cpp_Multi_Array_Test.cpp). Conflicts on the workflow yml files are less surprising. Can you make sense of this rebase PR? It does pass the tests on my end, and I think it's sensible.

**Comment by hellkite500** [comment]
Hmm....I rebased my branch with upstream/master and then cherry picked your commit, and the only conflict from [e448605](https://github.com/hellkite500/ngen/pull/5/commits/e44860585038693e57062835852850512d55146c), which was BMI_Module_Formulation.hpp, and it was a pretty easy one to resolve...

During the rebase, I resolved the following conflicts
- `test_bmi_cpp.hpp`
```diff
<<<<<<< HEAD
#include "bmi.hxx"
=======
#include <numeric>
#include <iostream>
#include "../extern/bmi-cxx/bmi.hxx"
>>>>>>> add an array variable that can be in/output from a model conditionally
```
to
```c++
#include "bmi.hxx"
#include <numeric>
#include <iostream>
```
- `Bmi_Module_Formulation.hpp`
```diff
<<<<<<< HEAD
                if (varItemSize != get_bmi_model()->GetVarNbytes(var_name)) {
                    throw std::runtime_error(
                            "BMI input variable '" + var_name + "' is an array - not currently supported");
                }
                double value = provider->get_value(CatchmentAggrDataSelector("",var_map_alias, model_epoch_time, t_delta,
                                                   get_bmi_model()->GetVarUnits(var_name)));
=======
                std::shared_ptr<void> value_ptr;
>>>>>>> use get_values interface for update calls when appropriate
```
to
```c++
std::shared_ptr<void> value_ptr;
```
- `test_and_validate.yml`
```diff
<<<<<<< HEAD
          targets: "test_bmi_multi"
          build-cores: ${{ env.LINUX_NUM_PROC_CORES }}
          bmi_c: 'ON'
          bmi_fortran: 'ON'
          use_python: 'ON'
          additional_python_requirements: 'extern/test_bmi_py/requirements.txt'

      - name: Run Unit Tests
=======
          path: .venv
          key: linux-py3-dependencies

      - name: Init Python Dependencies
        if: steps.cache-linux-py3-dependencies.outputs.cache-hit != 'true'
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install pip
          pip install numpy
          pip install -r extern/test_bmi_py/requirements.txt
          deactivate

      - name: Init Submodules
        run: git submodule update --init --recursive

      - name: cmake_init_test_lib_build
        run: cmake -B extern/test_bmi_fortran/cmake_build -S extern/test_bmi_fortran

      - name: build_test_bmi_fortran_shared_lib
        run: |
          cd extern/test_bmi_fortran/cmake_build
          make
          cd ../../../

      - name: cmake_init_fortran_iso_c_lib_build
        run: cmake -B extern/iso_c_fortran_bmi/cmake_build -S extern/iso_c_fortran_bmi

      - name: build_test_fortran_iso_c_shared_lib
        run: |
          cd extern/iso_c_fortran_bmi/cmake_build
          make
          cd ../../../

      - name: cmake_init_shared_lib_build
        run: cmake -B extern/test_bmi_cpp/cmake_build -S extern/test_bmi_cpp

      - name: build_test_bmi_cpp_shared_lib
        run: cmake --build extern/test_bmi_cpp/cmake_build --target testbmicppmodel

      - name: cmake_init_shared_lib_build
        run: cmake -B extern/test_bmi_c/cmake_build -S extern/test_bmi_c

      - name: build_test_bmi_c_shared_lib
        run: cmake --build extern/test_bmi_c/cmake_build --target testbmicmodel

      - name: Cache Boost Dependency
        id: cache-boost-dep
        uses: actions/cache@v1
        with:
          path: boost_1_72_0
          key: unix-boost-dep

      - name: Get Boost Dependency
        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
        run: |
          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
          tar xjf boost_1_72_0.tar.bz2

      - name: cmake_init_build
        run: |
          export BOOST_ROOT="$(pwd)/boost_1_72_0"
          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
          cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=ON -DBMI_FORTRAN_ACTIVE:BOOL=ON -DNGEN_ACTIVATE_PYTHON:BOOL=ON -DUDUNITS_ACTIVE:BOOL=ON -S .

      - name: build_bmi_multi_tests
        run: cmake --build cmake_build --target test_bmi_multi -- -j ${{ env.LINUX_NUM_PROC_CORES }}
        timeout-minutes: 15

      - name: run_bmi_multi_tests
>>>>>>> add test cpp bmi build to multi-bmi runner
```
to
```yaml
  targets: "test_bmi_multi"
          build-cores: ${{ env.LINUX_NUM_PROC_CORES }}
          bmi_c: 'ON'
          bmi_fortran: 'ON'
          use_python: 'ON'
          additional_python_requirements: 'extern/test_bmi_py/requirements.txt'

      - name: Run Unit Tests
```
and
```diff
<<<<<<< HEAD
          build-dir: ${{ steps.submod_build_2.outputs.build-dir }}
      - uses: ./.github/actions/clean-build
=======
          path: boost_1_72_0
          key: unix-boost-dep

      - name: Get Boost Dependency
        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
        run: |
          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.bz2
          tar xjf boost_1_72_0.tar.bz2

      - name: cmake_init_build
        run: |
          export BOOST_ROOT="$(pwd)/boost_1_72_0"
          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
          cmake -B cmake_build -DCMAKE_BUILD_TYPE=Debug -DBMI_C_LIB_ACTIVE:BOOL=ON -DNGEN_ACTIVATE_PYTHON:BOOL=ON -DUDUNITS_ACTIVE:BOOL=ON -S .

      - name: build_bmi_python_tests
        run: cmake --build cmake_build --target test_bmi_python -- -j ${{ env.MACOS_NUM_PROC_CORES }}
        timeout-minutes: 15

      - name: run_bmi_python_tests
        run: |
          cd ./cmake_build/test/
          ./test_bmi_python
          cd ../../
        timeout-minutes: 15

      - name: cleanup
        run: find . -name cmake_build -type d -delete


  # As with the BMI C MacOS job, separate multi BMI in linux tests to keep setups clean and cause of failures clear.
  test_bmi_multi_macos_latest:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache Python Dependencies
        id: cache-unix-py3-dependencies
        uses: actions/cache@v1
        with:
          path: .venv
          key: unix-py3-dependencies

      - name: Init Python Dependencies
        if: steps.cache-unix-py3-dependencies.outputs.cache-hit != 'true'
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install pip
          pip install numpy
          pip install -r extern/test_bmi_py/requirements.txt
          deactivate

      - name: Init Submodules
        run: git submodule update --init --recursive

      - name: cmake_init_test_lib_build
        run: cmake -B extern/test_bmi_fortran/cmake_build -DCMAKE_Fortran_COMPILER:FILEPATH=$(which gfortran-11) -S extern/test_bmi_fortran

      - name: build_test_bmi_fortran_shared_lib
        run: |
          cd extern/test_bmi_fortran/cmake_build
          make
          cd ../../../

      - name: cmake_init_fortran_iso_c_lib_build
        run: cmake -B extern/iso_c_fortran_bmi/cmake_build -DCMAKE_Fortran_COMPILER:FILEPATH=$(which gfortran-11) -S extern/iso_c_fortran_bmi

      - name: build_test_fortran_iso_c_shared_lib
        run: |
          cd extern/iso_c_fortran_bmi/cmake_build
          make
          cd ../../../

      - name: cmake_init_shared_lib_build
        run: cmake -B extern/test_bmi_cpp/cmake_build -S extern/test_bmi_cpp

      - name: build_test_bmi_cpp_shared_lib
        run: cmake --build extern/test_bmi_cpp/cmake_build --target testbmicppmodel

      - name: cmake_init_shared_lib_build
        run: cmake -B extern/test_bmi_c/cmake_build -S extern/test_bmi_c

      - name: build_test_bmi_c_shared_lib
        run: cmake --build extern/test_bmi_c/cmake_build --target testbmicmodel

      - name: Cache Boost Dependency
        id: cache-boost-dep
        uses: actions/cache@v1
>>>>>>> add test cpp bmi build to multi-bmi runner
```
to
```yaml
          build-dir: ${{ steps.submod_build_2.outputs.build-dir }}
      - uses: ./.github/actions/clean-build
```
Which, turns out, is just a `git rebase --skip` on this commit, cause after the change it is empty 🤦 

Then a `git cherry-pick e44860585038693e57062835852850512d55146c`
produced one final conflict in Bmi_Module_Formulation.hpp
```diff
<<<<<<< HEAD
        std::vector<double> get_values(const std::string &output_name, const time_t &init_time, const long &duration_s,
                                 const std::string &output_units) override{
=======
        std::vector<double> get_values(const CatchmentAggrDataSelector& selector, data_access::ReSampleMethod m=SUM) override
        {
            std::string output_name = selector.get_variable_name();
            time_t init_time = selector.get_init_time();
            long duration_s = selector.get_duration_secs();
            std::string output_units = selector.get_output_units();

>>>>>>> e44860585... Fixes to merge with #406
```
which resolves to
```c++
 std::vector<double> get_values(const CatchmentAggrDataSelector& selector, data_access::ReSampleMethod m=SUM) override
        {
            std::string output_name = selector.get_variable_name();
            time_t init_time = selector.get_init_time();
            long duration_s = selector.get_duration_secs();
            std::string output_units = selector.get_output_units();

```

My guess is you did something very similar in the original rebase resolution, but of course my branch doesn't know anything about that so all those conflicts are once again conflicts???

**Comment by hellkite500** [comment]
I could either force push my cleaned up branch or replicate the conflict resolution to merge this...

**Comment by mattw-nws** [comment]
Not particular on which way, but yeah if we think the merge is good lets get it in the PR.

There must be a better way to do this (in Git)  I just don't know it. That last change/conflict (`get_values(const std::string...` vs. `get_values(const CatchmentAggrDataSelector& selector...`) is an explicit edit I made, a straight-up change... but as a PR against your PR it is showing it as a conflict...which I guess makes some sense, but obviously isn't semantically what was intended.

**Pull request closed without merging**
